# -*- coding: utf-8 -*-
"""1_Full_Method.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IrdsRDwjfAXcVrjDCiTh5QbRcLVOimF2

# Fuzzy Graph Laplacian-Regularized Shallow Attention Neural Networks\n## Full Method Execution
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install scanpy
import os
import time
import psutil
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import pandas as pd
import scanpy as sc
from scipy.sparse import csr_matrix
from sklearn.metrics import adjusted_rand_score, normalized_mutual_info_score, roc_auc_score, f1_score
from scipy.spatial import cKDTree
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

# Define device
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

def log_telemetry(task_name, start_time):
    process = psutil.Process(os.getpid())
    mem_info = process.memory_info()
    ram_mb = mem_info.rss / (1024 ** 2)

    vram_mb = 0
    if torch.cuda.is_available():
        vram_mb = torch.cuda.memory_allocated() / (1024 ** 2)

    duration = time.time() - start_time

    telemetry = {
        "Task": task_name,
        "Duration_s": round(duration, 2),
        "RAM_MB": round(ram_mb, 2),
        "VRAM_MB": round(vram_mb, 2)
    }
    return telemetry

def preprocess_and_build_graph(h5ad_path, label_col='cell_type', k_neighbors=15):
    print(f"Loading data from {h5ad_path}...")
    start_time = time.time()

    if not os.path.exists(h5ad_path):
        print(f"File not found: {h5ad_path}. Generating SYNTHETIC dataset for demonstration...")
        # Generate synthetic data
        n_cells, n_genes = 2000, 500
        X = np.random.poisson(lam=0.5, size=(n_cells, n_genes)).astype(np.float32)
        # Add some structure for 3 classes
        labels = np.random.choice([0, 1, 2], size=n_cells)
        X[labels == 0, :50] += 2
        X[labels == 1, 50:100] += 2
        X[labels == 2, 100:150] += 2

        adata = sc.AnnData(X=csr_matrix(X))
        adata.obs[label_col] = labels.astype(str)
    else:
        adata = sc.read_h5ad(h5ad_path)

    print("Filtering cells and genes...")
    sc.pp.filter_cells(adata, min_genes=200)
    sc.pp.filter_genes(adata, min_cells=3)

    print("Normalizing (CPM) and scaling...")
    sc.pp.normalize_total(adata, target_sum=1e4)
    sc.pp.log1p(adata)
    sc.pp.scale(adata, max_value=10)

    # Map labels to integers
    unique_labels = adata.obs[label_col].unique()
    label_map = {lbl: i for i, lbl in enumerate(unique_labels)}
    y = np.array([label_map[l] for l in adata.obs[label_col]])

    print("Building Fuzzy Graph Laplacian...")
    X_dense = adata.X.toarray() if isinstance(adata.X, csr_matrix) else adata.X
    tree = cKDTree(X_dense)
    distances, indices = tree.query(X_dense, k=k_neighbors+1)

    # Adaptive bandwidth (k-th nearest neighbor distance)
    sigma = distances[:, -1]
    sigma = np.maximum(sigma, 1e-5) # avoid div by zero

    N = X_dense.shape[0]
    S = np.zeros((N, N))

    # Build sparse similarity matrix
    for i in range(N):
        for idx_j, j in enumerate(indices[i, 1:]): # skip self
            dist_sq = distances[i, idx_j+1]**2
            s_ij = np.exp(-dist_sq / (2 * sigma[i] * sigma[j]))
            S[i, j] = s_ij

    # Symmetrize
    S = np.maximum(S, S.T)

    # Degree matrix and Normalized Laplacian
    d = np.sum(S, axis=1)
    d_inv_sqrt = np.power(d, -0.5)
    d_inv_sqrt[np.isinf(d_inv_sqrt)] = 0.

    D_inv_sqrt = np.diag(d_inv_sqrt)
    L_sym = np.eye(N) - D_inv_sqrt @ S @ D_inv_sqrt

    tel = log_telemetry("Preprocessing & Graph Build", start_time)
    print(f"Preprocessing finished. {tel}")

    return torch.FloatTensor(X_dense), torch.FloatTensor(L_sym), torch.LongTensor(y), adata.var_names.values, label_map

# Entmax/Sparsemax activation proxy (simplified via softmax with temperature for stability)
def sparsemax(x, tau=0.1):
    return F.softmax(x / tau, dim=-1)

class GraphRegShallowAttention(nn.Module):
    def __init__(self, n_features, n_classes):
        super().__init__()
        self.theta = nn.Parameter(torch.randn(n_features))
        self.W1 = nn.Parameter(torch.randn(n_features, 64) * 0.01)
        self.b1 = nn.Parameter(torch.zeros(64))
        self.W2 = nn.Parameter(torch.randn(64, n_classes) * 0.01)
        self.b2 = nn.Parameter(torch.zeros(n_classes))

    def forward(self, X):
        alpha = sparsemax(self.theta)
        X_tilde = X * alpha
        H = F.leaky_relu(X_tilde @ self.W1 + self.b1)
        Y_hat_logits = H @ self.W2 + self.b2
        Y_hat = F.softmax(Y_hat_logits, dim=-1)
        return Y_hat, alpha

def train_model(X, L_sym, y, n_epochs=150, lr=1e-3, gamma=0.1, lambda_l1=1e-4):
    X = X.to(device)
    L_sym = L_sym.to(device)
    y = y.to(device)

    n_features = X.shape[1]
    n_classes = len(torch.unique(y))

    model = GraphRegShallowAttention(n_features, n_classes).to(device)
    optimizer = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=1e-4)

    start_time = time.time()

    for epoch in range(n_epochs):
        model.train()
        optimizer.zero_grad()

        Y_hat, alpha = model(X)

        # Cross Entropy
        loss_ce = F.cross_entropy(Y_hat, y)

        # Graph Regularization: Tr(Y^T L Y)
        loss_reg = gamma * torch.trace(Y_hat.T @ L_sym @ Y_hat)

        # L1 on attention weights
        loss_l1 = lambda_l1 * torch.sum(torch.abs(model.theta))

        loss = loss_ce + loss_reg + loss_l1

        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()

        if epoch % 50 == 0:
            print(f"Epoch {epoch} | Loss: {loss.item():.4f} | CE: {loss_ce.item():.4f} | Reg: {loss_reg.item():.4f}")

    tel = log_telemetry("Model Training", start_time)
    print(f"Training finished. {tel}")
    return model, tel

def evaluate_and_plot(model, X, y, label_map, var_names, prefix="full_model"):
    model.eval()
    with torch.no_grad():
        Y_hat, alpha = model(X.to(device))
        Y_pred = torch.argmax(Y_hat, dim=1).cpu().numpy()
        Y_prob = Y_hat.cpu().numpy()
        y_true = y.cpu().numpy()

    ari = adjusted_rand_score(y_true, Y_pred)
    nmi = normalized_mutual_info_score(y_true, Y_pred)
    f1 = f1_score(y_true, Y_pred, average='macro')
    try:
        roc = roc_auc_score(y_true, Y_prob, multi_class='ovr')
    except:
        roc = np.nan

    metrics = {
        "Model": prefix,
        "ARI": ari,
        "NMI": nmi,
        "F1_Macro": f1,
        "ROC_AUC": roc
    }

    print(f"Metrics for {prefix}: ARI={ari:.4f}, NMI={nmi:.4f}, F1={f1:.4f}, ROC={roc:.4f}")

    # Biomarker Extraction
    alpha_np = alpha.cpu().numpy()
    top_k = min(1500, len(alpha_np))
    top_indices = np.argsort(alpha_np)[::-1][:top_k]
    top_genes = var_names[top_indices]
    top_scores = alpha_np[top_indices]

    df_bio = pd.DataFrame({
        'Biomarker_Name': top_genes,
        'Original_Index': top_indices,
        'Attention_Score': top_scores
    })
    csv_name = f"{prefix}_top_{top_k}_biomarkers.csv"
    df_bio.to_csv(csv_name, index=False)
    print(f"Saved top {top_k} biomarkers to {csv_name}")

    # Plotting
    plt.figure(figsize=(10, 5))
    sns.histplot(alpha.cpu().numpy(), bins=100, kde=True)
    plt.title(f"Attention Weights Distribution ({prefix})")
    plt.xlabel("Attention Score")
    plt.ylabel("Frequency")
    plt.savefig(f"{prefix}_attention_dist.png", dpi=300, bbox_inches='tight')
    plt.savefig(f"{prefix}_attention_dist.eps", format='eps', bbox_inches='tight')
    plt.close()

    return metrics

# Execution Block
h5ad_file = "/content/c2cb4260-9389-4392-8b35-5b867ef1ec85.h5ad" # REPLACE WITH YOUR UPLOADED FILE PATH
X, L_sym, y, var_names, label_map = preprocess_and_build_graph(h5ad_file)

model, tel = train_model(X, L_sym, y, n_epochs=350)
metrics = evaluate_and_plot(model, X, y, label_map, var_names, prefix="Model_Full")

pd.DataFrame([metrics]).to_csv("Model_Full_Metrics.csv", index=False)
pd.DataFrame([tel]).to_csv("Model_Full_Telemetry.csv", index=False)
print("Pipeline complete. Artifacts saved.")